#!/bin/bash
branches=$(git branch --no-color -vv | grep ': gone]' | grep -v "\*" | awk '{ print $1; }' | grep -vE '^(main|master|develop|release/.*)$')
[ -n "$branches" ] && echo "$branches" | xargs git branch -D
