#!/bin/bash

echo "Export installed Brew/cask/mas packages to ~/.Brewfile"
brew bundle dump --global --force

echo "Export installed Fish Modules to ~/.fisher-list"
fisher list > ~/.fisher-list

echo "done, opening VS code to allow for file washing"
code -w  ~/.Brewfile ~/.fisher-list

echo "Will save files to repo"
yadm add ~/.Brewfile ~/.fisher-list
yadm commit -m "Updated fish plugins and brew install list"
yadm push
