[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'

[aws]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[kubernetes]
disabled = false

[kubernetes.context_aliases]
"*minikube*" = "minikube"

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_range = "08:00:00-16:00:00"
