#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ];then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
 #Set iterm2 config
  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
  fi
  if [ ! -f ~/.iterm2_shell_integration.zsh ]; then
    echo "Installing iTerm2 Shell intitration for zsh"
    curl -L https://iterm2.com/shell_integration/zsh -o ~/.iterm2_shell_integration.zsh
  fi

fi

#Install VScode addons
if [ $commands[code] ]; then
  echo "Installing Visual Studio Code extentions"
  .~/.vscodeextentions
fi


if [ "$system_type" = "Linux" ]; then
  #Install apt packages
  echo "Installing YADM (sudo is required)"
  sudo apt-get install -y yadm zsh
  if command -v snap >/dev/null 2>&1; then
    snap install antibody -y
  fi
fi
# @todo check if the snap install yadm code is correct


if [ "$system_type" = "Linux" ]; then
  echo "Update/Upgrade apt (sudo is required)"
  sudo apt-get update
  sudo apt-get dist-upgrade -y --force-confold
fi

if [ "$system_type" = "Darwin" ]; then
  echo "Configuring MacOS Settings"
  # Show remaining battery time; hide percentage
  defaults write com.apple.menuextra.battery ShowPercent -string "NO"
  defaults write com.apple.menuextra.battery ShowTime -string "YES"
  # Expand save panel by default
  defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
  # Expand print panel by default
  defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
  # Disable opening and closing window animations
  defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
  # Disable Mission Control Animations
  defaults write com.apple.dock expose-animation-duration -int 0
  # Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
  defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
  # Disable auto-correct
  defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
  # Require password immediately after sleep or screen saver begins
  defaults write com.apple.screensaver askForPassword -int 1
  defaults write com.apple.screensaver askForPasswordDelay -int 0
  # Show status bar in Finder
  defaults write com.apple.finder ShowStatusBar -bool true
  # Allow text selection in Quick Look
  defaults write com.apple.finder QLEnableTextSelection -bool true
  # Display full POSIX path as Finder window title
  defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
  # Avoid creating .DS_Store files on network volumes
  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
  # Disable the warning when changing a file extension
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
  # Disable the warning before emptying the Trash
  defaults write com.apple.finder WarnOnEmptyTrash -bool false
  # Empty Trash securely by default
  defaults write com.apple.finder EmptyTrashSecurely -bool true
  # Show indicator lights for open applications in the Dock
  defaults write com.apple.dock show-process-indicators -bool true
  # Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
  defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false
  # Prevent Time Machine from prompting to use new hard drives as backup volume
  defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
  # Configure Apple Dock
  defaults write com.apple.dock static-only -bool TRUE
  defaults write com.apple.dock autohide -bool TRUE
  defaults write com.apple.dock showhidden -bool TRUE
  defaults write com.apple.dock tilesize 25
  defaults write com.apple.dock mineffect suck

  #Restart Apple Dock
  killall Dock

fi


#Post tasks
echo "remove Temp YADM binary"
rm -f "$HOME/yadm"
echo "Setting remote url to git instead of http"
yadm remote set-url origin "git@github.com:lonix/dotfiles.git"
echo "Changing shell to ZSH."
chsh -s /bin/zsh
