---
name: "YADM bootstrap"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    env:
      CI: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Xcode command line tools
      run: xcode-select --install
      if: runner.os == 'macos-latest'


    - name: Install YADM
      run: |
        curl -fLo ~/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x ~/yadm

    - name: List files in home directory
      run: ls -la ~

    - name: Clone and bootstrap dotfiles
      run: |
        ./yadm clone https://github.com/lonix/dotfiles.git --bootstrap
