name: "YADM bootstrap"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    env:
      CI: true
    steps:
      - name: fetch YADM
        run: |
          curl -fLo yadm.sh https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x yadm.sh
          cat yadm.sh
      - name: Go bootstrap
        run: ./yadm.sh clone https://github.com/lonix/dotfiles.git --bootstrap
