---
name: "YADM bootstrap"

on:
  push:
    branches:
      - master
  pull_request: # Add pull_request event
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    env:
      CI: true
    steps:
    - name: Install YADM
      run: |
        curl -fLo ~/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x ~/yadm
        ~/yadm version
    - name: Clone dotfiles
      run: |
        cd ~
        ~/yadm clone https://github.com/lonix/dotfiles.git
    - name: run bootstrap script
      run: |
        cd ~
        ~/yadm bootstrap
