name: "YADM bootstrap"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, ubuntu-20.04, ubuntu-18.04]
    env:
      CI: true
    steps:
      - name: fetch YADM
        run: curl -fLo ~/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x ~/yadm
      - name: Go bootstrap
        run: ./yadm clone https://github.com/lonix/dotfiles.git --bootstrap
