name: Lint Code base

on: [push]

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Linting
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
